#script to create index files for each bible from files generated by rename.rb
#should be re-written to be included in rename.rb
require 'rexml/document'
require 'fileutils'

#default to current directory if none provided
directory = ARGV[0] ? ARGV[0] : Dir.pwd

#get index of OSIS books
booksXML = REXML::Document.new(File.new("../data/books.xml"))

#get index of ISO languages
isoLangFile = File.new("../data/ISO-639-2_utf-8.txt",'r');
lang = Hash.new
while (line = isoLangFile.gets)
	a = line.split('|')
	id = a[2]; #using old ISO-639-1 codes for now
	if id
		lang[id] = a[3] #english title for language
	end
end
isoLangFile.close

Dir.chdir(directory);

indexFile = File.new("index.xml","w+");
indexXML = REXML::Document.new();
a = indexXML.add_element "bibles"
indexXML << REXML::XMLDecl.new

Dir.glob("*") do |lang_entry| 

	if File.directory? lang_entry 
		title = lang[lang_entry] ? lang[lang_entry] : "Other"
		b = a.add_element "language", {"id"=>lang_entry, "title"=>title}
		Dir.foreach(lang_entry) do |bible_entry|
			if bible_entry != '.' && bible_entry != '..' && (File.directory? lang_entry+'/'+bible_entry)
				firstBook = Dir.glob(lang_entry+'/'+bible_entry+'/*.xml')[0]
				if firstBook
					firstBookXML = REXML::Document.new(File.new(firstBook))
					title = firstBookXML.root.elements["osisText/header/work/title"].text	
					title = title ? title : "Unknown"				
					puts lang_entry+'/'+bible_entry+': '+title
					b.add_element "bible", {"id"=>bible_entry,"title"=>title}
				end
			end
		end
	end
end
indexFile.write(indexXML)